version: "3.9"
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: ["server", "/data", "--console-address", ":9001"]
    restart: always
    networks:
      - my-booking-network

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-booking-network

  booking:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - minio
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MINIO_ENDPOINT: minio
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./:/app
      - /app/node_modules
    # restart: always
    networks:
      - my-booking-network
    # command: ["nodemon", "--exec", "ts-node", "src/index.ts"]

volumes:
  minio-data:
  postgres-data:

networks:
  my-booking-network:
