export enum ROLE_TYPE {
  CUSTOMER = "CUSTOMER",
  RECEPTIONIST = "RECEPTIONIST",
  MANAGER = "MANAGER",
  ADMIN = "ADMIN",
}

export enum ROOM_STATUS {
  AVAILABLE = "AVAILABLE",
  UNAVAILABLE = "UNAVAILABLE",
}

export enum BOOKING_STATUS {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  CHECKED_IN = "CHECKED_IN",
  CHECKED_OUT = "CHECKED_OUT",
  CANCELED = "CANCELED",
}

export enum GENDER {
  MALE = "MALE",
  FEMALE = "FEMALE",
  OTHER = "OTHER",
}

export enum DISCOUNT_TYPE {
  PERCENTAGE = "PERCENTAGE",
  FIXED_AMOUNT = "FIXED_AMOUNT",
}

export enum STAFF_ROLE {
  MANAGER = "MANAGER",
  RECEPTIONIST = "RECEPTIONIST",
}

export enum BED_TYPE {
  SINGLE = "SINGLE",
  DOUBLE = "DOUBLE",
  QUEEN = "QUEEN",
  KING = "KING",
  TWIN = "TWIN",
  FULL = "FULL",
  CALIFORNIA_KING = "CALIFORNIA_KING",
  SOFA_BED = "SOFA_BED",
  BUNK_BED = "BUNK_BED",
  ROLL_AWAY = "ROLL_AWAY",
  MURPHY_BED = "MURPHY_BED",
}

export enum ROOM_TYPE {
  SINGLE = "SINGLE",
  DOUBLE = "DOUBLE",
  TWIN = "TWIN",
  FAMILY = "FAMILY",
  SUITE = "SUITE",
  QUEEN = "QUEEN",
  KING = "KING",
  PRESIDENTIAL_SUITE = "PRESIDENTIAL_SUITE",
  DELUXE = "DELUXE",
  STANDARD = "STANDARD",
  STUDIO = "STUDIO",
  DORMITORY = "DORMITORY",
  CONNECTING = "CONNECTING",
}
