export const myBookings = [
  {
    id: 2535276,
    orderCode: "H2535276",
    orderToken: "46bcf29a-2aa9-45c5-b159-419486b5dcf1",
    hotel: {},
    checkIn: "03-05-2024",
    checkOut: "08-05-2024",
    numAdults: 8,
    numChildren: 3,
    numRooms: 4,
    childrenAges: [10, 5, 4],
    customerId: 2183063,
    freeBreakfast: true,
    freeCancellation: false,
    bookingDate: "2024-05-02 11:17:01",
    expiredTime: "2024-05-02 23:59:00",
    paymentStatus: "waiting",
    bookingStatus: "waiting",
    basePrice: 2978974,
    priceWithoutBookerMarkup: 3294000,
    price: 3294000,
    totalRoomPrice: 65880000,
    promotionCode: "IMPE400",
    discount: 8000000,
    finalPrice: 57880000,
    customerPrice: 65880000,
    paymentMethodFee: 0,
    totalPrice: 65880000,
    paymentMethod: "Chưa thanh toán",
    paymentMethodId: 99,
    paymentMethodCode: "NPM",
    includedVAT: true,
    customer: {
      name: "Jackson Cook",
      phone: "+844535345353",
      email: "compareburden8600@gmail.com",
      address: "",
    },
    invoiceInfo: {},
    roomBookings: [
      {
        name: "Deluxe King Seaview (Khu Căn Hộ hoặc Khu Khách Sạn)",
        numAdult: 2,
        numChildren: 1,
        freeBreakfast: true,
        freeCancellation: false,
        refundable: true,
        quantity: 1,
        childrenAges: [10],
        bedTypes: ["1 giường King"],
        hotelCancellationPolicies: [
          {
            dateFrom: null,
            dateTo: "03/05/2024 15:00:00",
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
          {
            dateFrom: "03/05/2024 15:00:00",
            dateTo: null,
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
        ],
        noSmoking: false,
        isHighFloor: false,
        specialRequest: null,
        contactName: "Jackson Cook",
        phoneNumber: "4535345353",
        contactEmail: "compareburden8600@gmail.com",
        totalBasePrice: 14894868,
        totalTaxAndFee: 2045916,
        totalSurcharge: 1080000,
        totalSystemFee: 0,
        totalDiscount: -742066,
        checkInHour: "16:00-17:00",
        checkOutHour: null,
        partnerRoomBookingCode: "MT10403072131ZM",
        nightlyPrices: null,
      },
      {
        name: "Deluxe King Seaview (Khu Căn Hộ hoặc Khu Khách Sạn)",
        numAdult: 2,
        numChildren: 1,
        freeBreakfast: true,
        freeCancellation: false,
        refundable: true,
        quantity: 1,
        childrenAges: [5],
        bedTypes: ["1 giường King"],
        hotelCancellationPolicies: [
          {
            dateFrom: null,
            dateTo: "03/05/2024 15:00:00",
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
          {
            dateFrom: "03/05/2024 15:00:00",
            dateTo: null,
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
        ],
        noSmoking: false,
        isHighFloor: false,
        specialRequest: null,
        contactName: "Jackson Cook",
        phoneNumber: "4535345353",
        contactEmail: "compareburden8600@gmail.com",
        totalBasePrice: 14894868,
        totalTaxAndFee: 2045916,
        totalSurcharge: 0,
        totalSystemFee: 0,
        totalDiscount: -742066,
        checkInHour: "16:00-17:00",
        checkOutHour: null,
        partnerRoomBookingCode: "MT10403072132JE",
        nightlyPrices: null,
      },
      {
        name: "Deluxe King Seaview (Khu Căn Hộ hoặc Khu Khách Sạn)",
        numAdult: 2,
        numChildren: 1,
        freeBreakfast: true,
        freeCancellation: false,
        refundable: true,
        quantity: 1,
        childrenAges: [4],
        bedTypes: ["1 giường King"],
        hotelCancellationPolicies: [
          {
            dateFrom: null,
            dateTo: "03/05/2024 15:00:00",
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
          {
            dateFrom: "03/05/2024 15:00:00",
            dateTo: null,
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
        ],
        noSmoking: false,
        isHighFloor: false,
        specialRequest: null,
        contactName: "Jackson Cook",
        phoneNumber: "4535345353",
        contactEmail: "compareburden8600@gmail.com",
        totalBasePrice: 14894868,
        totalTaxAndFee: 2045916,
        totalSurcharge: 0,
        totalSystemFee: 0,
        totalDiscount: -742066,
        checkInHour: "16:00-17:00",
        checkOutHour: null,
        partnerRoomBookingCode: "MT10403072133HM",
        nightlyPrices: null,
      },
      {
        name: "Deluxe King Seaview (Khu Căn Hộ hoặc Khu Khách Sạn)",
        numAdult: 2,
        numChildren: 0,
        freeBreakfast: true,
        freeCancellation: false,
        refundable: true,
        quantity: 1,
        childrenAges: [],
        bedTypes: ["1 giường King"],
        hotelCancellationPolicies: [
          {
            dateFrom: null,
            dateTo: "03/05/2024 15:00:00",
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
          {
            dateFrom: "03/05/2024 15:00:00",
            dateTo: null,
            refundAmount: 0,
            price: 57880000,
            percent: 0,
            cancellationType: "amount",
          },
        ],
        noSmoking: false,
        isHighFloor: false,
        specialRequest: null,
        contactName: "Jackson Cook",
        phoneNumber: "4535345353",
        contactEmail: "compareburden8600@gmail.com",
        totalBasePrice: 14894868,
        totalTaxAndFee: 2045916,
        totalSurcharge: 0,
        totalSystemFee: 0,
        totalDiscount: -742066,
        checkInHour: "16:00-17:00",
        checkOutHour: null,
        partnerRoomBookingCode: "MT10403072134HY",
        nightlyPrices: null,
      },
    ],
    cancelPolicies: [
      "Nếu hủy phòng trước 15:00 ngày 03/05, chúng tôi sẽ thu 65.760.000 đ phí hủy phòng.",
      "Nếu hủy phòng từ 15:00 ngày 03/05, chúng tôi sẽ thu 65.875.000 đ phí hủy phòng.",
    ],
  },
];
